### ISSUE TITLE
Help with building and installing Intel Wifi kext !?

### ISSUE THREAD

**Issue by ghost** [zxystd/AppleIntelWifiAdapter#10]
Hi, can you help me / show me how to build kext Intel Wifi from this link: https://github.com/zxystd/AppleIntelWifiAdapter/tree/feature-rewrite-all

I'm quite know everything about Hackintosh but not to be a perfect one, so I want to keep learning from each other. But I have to admit I don't know how to build kext with terminal and Xcode, just using kext release :''D....

**Comment by williambj1** [comment]
I think its better to practice with a stable and usable kext rather than this one which is still work in progress. Building this unfinished experimental kext makes no sense and can be reasonably considered as a waste of time if you are not debugging IOKit stuff.

**Comment by ghost** [comment]
> I think its better to practice with a stable and usable kext rather than this one which is still work in progress. Building this unfinished experimental kext makes no sense and can be reasonably considered as a waste of time if you are not debugging IOKit stuff.

Okay thanks a lot for your advice but I see nowhere Intel wifi kext to download and use it, so I think the only way is build kext with xcode :( ...

**Comment by williambj1** [comment]
It’s still work in progress and doesn’t work now. Wait and see the magic.

Another developer has a working 7xxx kext, please refer to #6
