### ISSUE TITLE
Only HW steps B and C are currently supported (0x312)

### ISSUE THREAD

**Issue by averycblack** [zxystd/AppleIntelWifiAdapter#13]
Hello, was wondering what this error meant?
I've been messing around a bit with this trying to get firmware to load onto my AC 9560 and skipping this check at IWLMvmdriver:Start() (line 261) seems to allow firmware upload just fine, though it timeouts afterwards.

![image](https://user-images.githubusercontent.com/13190749/74612849-2439d680-50be-11ea-8ed3-c20d9d195dd0.png)

What would it take to make this work with SILICONE_A_STEP?

**Comment by zxystd** [comment]
It can upload firmware now, the log figure out that the firnware not match your device, I have seem this error on my test device 3165, and after replace firmware iwlwifi-7265D-**29**.ucode to iwlwifi-7265D-**27**.ucode, it works. I think the firmware's version are too high, I don't have 9000 serials device, maybe you can have a try help me to test like what I do.

**Comment by averycblack** [comment]
Figured it out. The fix was just pulled in from the last pull request.
I'm gonna put in a pull request for the 9000 series, as I had to do a few things to fix it.

Edit: Here's a pic
![image](https://user-images.githubusercontent.com/13190749/74806730-a3d0cc80-529b-11ea-87db-f7300cfa7528.png)
