### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by williambj1** [zxystd/AppleIntelWifiAdapter#4]
@zxystd 

我在远景论坛上看到有人开发了 `7265ac` 的驱动，请问和您是同一个人吗，谢谢！

http://bbs.pcbeta.com/viewthread-1838489-1-1.html

远景上的驱动的 `NSHumanReadableCopyright` 和 驱动的名称都与您的驱动不同，并且根据另一个 issue 里的消息所述您似乎没有 `7265ac` 这个网卡

感谢大佬的付出！

**Comment by zxystd** [comment]
> @zxystd
> 
> 我在远景论坛上看到有人开发了 `7265ac` 的驱动，请问和您是同一个人吗，谢谢！
> 
> http://bbs.pcbeta.com/viewthread-1838489-1-1.html
> 
> 远景上的驱动的 `NSHumanReadableCopyright` 和 驱动的名称都与您的驱动不同，并且根据另一个 issue 里的消息所述您似乎没有 `7265ac` 这个网卡
> 
> 感谢大佬的付出！

那个不是我哦，我这个只是初步实现了80211的调用，目前在维护隔壁的蓝牙项目，有时间才会维护这个。谢谢支持。

**Comment by williambj1** [comment]
隔壁的蓝牙固件已经成功让本子里的 9560ac 蓝牙 工作了，谢谢大佬的付出！
